name: MemoMate
on:
  push:
    branches: ["master"]
jobs:
  build:
    runs-on: self-hosted
    environment: production
    strategy:
      matrix:
        node-version: [22.x]
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.node-version }}
          cache: 'npm'

      - name: Generate .env file
        run: |
          echo "VITE_API_URL=${{ secrets.API_URL }}" >> .env

      - name: Install dependencies
        run: npm ci

      - name: Build app
        run: npm run build

      - name: Deploy
        run: rsync -av --checksum --delete --no-times --chown=www-data:www-data --chmod=F775,D775 ./dist/ ${{ secrets.WEB_ROOT_PATH }}
